denses_params: [64, 32, 16]
activation: "relu"
epochs: 50
batch_size: 32
dataset:
  name: "boston"
  path: "nn_from_scratch/model/generate/data/${dataset.name}/data.py"
  args:
    random_seed: 42
random_seed: 42
