name: Run code quality checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  code_quality_check:
    name: Run code quality checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements_test.txt

      - name: Run ruff
        run: |
          ruff check nn_from_scratch

      - name: Run mypy
        run: |
          mypy nn_from_scratch --install-types --non-interactive
